{% set name = "sidpy" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44b59c0bf9642f82197e3fd18434785671e2ef1d8aff115c8f3a2c1c8aff6408

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - pytest-runner
  run:
    - python >=3
    - numpy >=1.10
    - dask >=0.10
    - h5py >=2.6.0
    - matplotlib-base >=2.0.0
    - psutil
    - six
    - joblib >=0.11.0
    - ipywidgets >=5.2.2
    - ipython

test:
  imports:
    - sidpy

about:
  home: https://github.com/pycroscopy/sidpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python utilities for storing, visualizing, and processing Spectroscopic and Imaging Data (SID)
  doc_url: https://pycroscopy.github.io/sidpy/about.html
  dev_url: https://github.com/pycroscopy/sidpy

extra:
  recipe-maintainers:
    - ssomnath
    - carlodri
