{% set name = "sidpy" %}
{% set version = "0.12.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d21dda63a156bfaf42abf0576129fef0370f1cbc7535e2adc46a6464d74e8529

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.10
    - dask-core >=0.10
    - h5py >=2.6.0
    - matplotlib-base >=2.0.0
    - distributed >=2.0.0
    - psutil
    - six
    - ipyfilechooser >=0.0.6
    - joblib >=0.11.0
    - ipywidgets >=5.2.2
    - ipython
    - scikit-learn
    - scipy
    - ase
    - ipykernel
    - ipympl
    - dill

test:
  imports:
    - sidpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pycroscopy/sidpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python utilities for storing, visualizing, and processing Spectroscopic and Imaging Data (SID)
  doc_url: https://pycroscopy.github.io/sidpy/about.html
  dev_url: https://github.com/pycroscopy/sidpy

extra:
  recipe-maintainers:
    - ssomnath
    - ramav87
    - gduscher
    - carlodri
    - jan-janssen
