{% set name = "sidpy" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25a7467c5d9d300aa46188e16e0e1ae4ef9404cd3d28e93e5e8d8c24c26f5e0d
  patches:
    - scikitlearn.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - pytest-runner
  run:
    - python >=3
    - numpy >=1.10
    - dask >=0.10
    - h5py >=2.6.0
    - matplotlib-base >=2.0.0
    - distributed >=2.0.0
    - psutil
    - six
    - ipyfilechooser >=0.0.6
    - joblib >=0.11.0
    - ipywidgets >=5.2.2
    - ipython
    - scikit-learn
    - scipy

test:
  imports:
    - sidpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pycroscopy/sidpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python utilities for storing, visualizing, and processing Spectroscopic and Imaging Data (SID)
  doc_url: https://pycroscopy.github.io/sidpy/about.html
  dev_url: https://github.com/pycroscopy/sidpy

extra:
  recipe-maintainers:
    - ssomnath
    - ramav87
    - gduscher
    - carlodri
    - jan-janssen
