schema_version: 1

context:
  name: sidpy
  version: 0.12.9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 7b81a74c8bb57e93d92f9531c1defea10ead5ea25a65d3d4194ca02af999d18e

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - pytest-runner
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy >=1.10
    - dask-core >=0.10
    - h5py >=2.6.0
    - matplotlib-base >=2.0.0
    - distributed >=2.0.0
    - psutil
    - six
    - ipyfilechooser >=0.0.6
    - joblib >=0.11.0
    - ipywidgets >=5.2.2
    - ipython
    - scikit-learn
    - scipy
    - ase
    - ipykernel
    - ipympl
    - dill
    - dask-ml
    - pyswarms

tests:
  - python:
      imports:
        - sidpy
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: MIT
  license_file: LICENSE
  summary: Python utilities for storing, visualizing, and processing Spectroscopic and Imaging Data (SID)
  homepage: https://github.com/pycroscopy/sidpy
  repository: https://github.com/pycroscopy/sidpy
  documentation: https://pycroscopy.github.io/sidpy/about.html

extra:
  recipe-maintainers:
    - ssomnath
    - ramav87
    - gduscher
    - carlodri
    - jan-janssen
